### 배열 자동 생성
* random을 통해서 자동으로 생성가능함
* randint(start, end, size = (row size, column size)) 형태로 사용 (end는 포함되지 않음)

In [ ]:
import numpy as np

In [ ]:
arr1 = np.random.randint(0,10, size=(2,3))  # 0~9로 이루어진 2 x 3 배열 만들기
print(arr1)

arr2 = np.random.randint(0,10, size = 10)   # 0~9로 이루어진 10개짜리 1차원 배열 만들기
print(arr2)

[[1 3 7]
 [5 6 9]]
[7 8 1 6 2 7 0 5 5 4]


* rand(row size, column size)는 0~1 사이의 값을 랜덤 선택 (1은 미포함)


In [ ]:
arr3 = np.random.rand(5,3)
print(arr3)

[[0.38763131 0.76421646 0.02417704]
 [0.59622183 0.06823978 0.31965865]
 [0.61432849 0.49722564 0.19413192]
 [0.08523269 0.77049334 0.45554028]
 [0.82799773 0.96622609 0.68986094]]


In [ ]:
arr4 = np.random.rand(5,3)
print(arr4)

[[0.05607317 0.44727455 0.48972326]
 [0.76182447 0.12808405 0.77442286]
 [0.11720858 0.01293112 0.67401956]
 [0.62131091 0.2570773  0.41069205]
 [0.78195655 0.13591799 0.54868227]]


### 주요 통계값
* 리스트와 마찬가지로 min(), count() 등 되며
* 평균 및 표준편차도 쉽게 구할 수 있다 mean(), std() 

In [ ]:
print(arr4.sum())
print(arr4.min())
print(arr4.max())
print(arr4.mean()) # 평균
print(arr4.std()) # 표준편차
print(arr4.var()) # 분산


6.217198694023214
0.012931116075698523
0.781956550090538
0.4144799129348809
0.2686521669848678
0.0721739868256653


### 특정 범위 가져오기
* arr[start:end:step]으로 특정 범위 데이터를 가져올 수 있다
  (end 는 미포함)
* 리스트와 동일함
* 0부터 시작, 첫번째 요소는 0번임

In [ ]:
arr5 = np.random.randint(10, size = 10)
print(arr5)

[0 0 5 6 1 9 8 7 2 9]


In [ ]:
arr5[:5] # 0~4번째 값을 가져온다. 

array([0, 0, 5, 6, 1])

In [ ]:
arr5[1:3]

array([0, 5])