# Numpy Basic

* 딥러닝 프레임워크는 Matrix(행렬) 기반 연산을 하며, 파이썬의 Numpy 패키지와 호환되며 대부분 함수의 사용법이 Numpy와 유사합니다. 

* numpy의 array는 list와 유사하나 특화 기능이 조금 다릅니다. 
* numpy 배열과 list는 쉽게 변환 가능합니다
* 리스트는 문자, 숫자, 리스트 등 다양한 요소를 넣을 수 있으나, numpy array는 한가지 데이터 타입만 저장 가능합니다

* numpy array는 list와 달리 배열이 바로 연산 가능합니다

리스트 사용 예시

In [ ]:
# 리스트 사용으로 각 항목에 100을 더하는 경우
num = [1,3,4,8,-1]

num_100=[]
for i in num:
  num_100.append(i+100)
print(num_100)

[101, 103, 104, 108, 99]


List Comprehension: 조금 더 간단하게 리스트를 만들 수 있습니다. 



In [ ]:
# 리스트에서 각각의 요소에 100을 더하는 경우
num = [1,3,4,8,-1]
num_100 = [i+100 for i in num] #list comprehension
print(num_100)

[101, 103, 104, 108, 99]


Numpy 사용시

* np.array()를 통해 리스트를 numpy array로 바꿀 수 있습니다

In [ ]:
# numpy array 연산
import numpy as np
num = [1,3,4,8,-1]
num_arr = np.array(num) # 리스트를 numpy array로 변경
num_arr

array([ 1,  3,  4,  8, -1])

In [ ]:
type(num_arr)

numpy.ndarray

Numpy 배열은 숫자를 더하면 모든 요소에 적용됩니다

사칙연산에 대해 동일하게 적용됩니다

In [ ]:
num_100 = num_arr + 100
print(num_100)

[101 103 104 108  99]


배열끼리도 연산이 됩니다. 
* 배열끼리의 연산이 되므로 코딩이 매우 간결해집니다
* 같은 사이즈의 배열끼리 연산해봅시다

In [ ]:
# numpy 활용
year_18 = [100,200,210, 300]
year_19 = [110,220,300, 350]
year_18_np = np.array(year_18)
year_19_np = np.array(year_19)

# 배열끼리 빼봅시다
rev_diff = year_19_np-year_18_np
print(rev_diff)

[10 20 90 50]


##### 2차 배열(행렬) 만들기
* numpy는 행렬 연산이 가능합니다
* 특정 요소를 가져오는 방법은 리스트와 동일하게 [숫자]로 가져오면 됩니다. 

* 인덱스는 0번부터 시작입니다. 첫번째 요소를 가져오려면 [0]을 사용합니다

In [ ]:
# 리스트 2차 배열 형태로 만들기
data_2d = [[1,2,3], [4,5,6], [7,8,9]]
print(data_2d)
print(data_2d[0])
print(data_2d[0][1])

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
[1, 2, 3]
2


2차원 리스트를 np.array를 사용하여 2차원 numpy 배열로 만들 수 있습니다

In [ ]:
# numpy 2d array로 변경
data_2d_arr = np.array(data_2d)
print(data_2d_arr)
print(data_2d_arr[0][1])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
2


##### 행렬 연산
* 2d array도 연산이 가능합니다
* 사칙연산을 해봅시다


In [ ]:
arr1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2 = np.array([[3,4,5],[6,7,8],[9,10,11]])
print(arr1)
print(arr2)
print(arr2-arr1)
print(arr2*arr1)
print(arr2/arr1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[2 2 2]
 [2 2 2]
 [2 2 2]]
[[ 3  8 15]
 [24 35 48]
 [63 80 99]]
[[3.         2.         1.66666667]
 [1.5        1.4        1.33333333]
 [1.28571429 1.25       1.22222222]]


행렬 연산도 가능합니다
* 행렬 곱은 @ 또는 np.dot()을 사용하면 됩니다
* 전치행렬은 transpose() 또는 T를 사용합니다

In [ ]:
arr1 @ arr2

array([[ 42,  48,  54],
       [ 96, 111, 126],
       [150, 174, 198]])

In [ ]:
np.dot(arr1, arr2)

array([[ 42,  48,  54],
       [ 96, 111, 126],
       [150, 174, 198]])

In [ ]:
# transpose (전치행렬)
# 행렬을 바꿈
arr1.transpose()

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [ ]:
arr1.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])