텐서플로우는 딥러닝 연산을 위해 Tensor라는 데이터 형태를 정의하여 사용합니다. 

* Numpy의 기능과 유사한 형태로 사용할 수 있게 만들어져 있습니다. 



참고링크: https://www.tensorflow.org/guide/tensor

In [2]:
import tensorflow as tf

상수 만들기

constant를 사용하여 상수를 저장할 수 있습니다

int32는 32비트 정수형을 의미합니다

float은 실수입니다. 뒤의 숫자는 변수의 사이즈입니다

In [3]:
# 변수에 값과 배열을 넣어봅시다
a = tf.constant(3)
a

<tf.Tensor: shape=(), dtype=int32, numpy=3>

변수.numpy()를 통해 numpy 배열로 손쉽게 변경됩니다

In [4]:
# numpy 변환
b=a.numpy()

In [5]:
type(b)

numpy.int32

Numpy와 동일하게 숫자를 더하거나 사칙연산을 하면 모든 요소에 적용됩니다

In [6]:
arr = tf.constant([[1,2], [3,4]])

In [7]:
arr

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [8]:
arr+3

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[4, 5],
       [6, 7]], dtype=int32)>

In [ ]:
arr*3

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 3,  6],
       [ 9, 12]], dtype=int32)>

Numpy와 동일하게 배열간 연산도 지원합니다

행렬곱 연산도 지원합니다

In [ ]:
arr2 = tf.constant([[3,4], [5,6]])

In [ ]:
arr+arr2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 4,  6],
       [ 8, 10]], dtype=int32)>

In [ ]:
arr*arr2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 3,  8],
       [15, 24]], dtype=int32)>

In [ ]:
arr@arr2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[13, 16],
       [29, 36]], dtype=int32)>

최대값이 몇번째 위치하는지 argmax라는 함수를 통해 알 수 있습니다. (Numpy도 동일한 함수가 있습니다)

딥러닝에서 최종 모델이 가장 높은 확률로 선택한 값이 무엇인지 확인할 때 사용합니다.

In [9]:
tf.argmax(arr)

<tf.Tensor: shape=(2,), dtype=int64, numpy=array([1, 1])>

Indexing도 Numpy와 동일한 방식으로 사용합니다

In [10]:
arr3 = tf.constant([1,2,3,4,5])

In [14]:
arr3[:3]  # 0~2번째 요소 가져오기

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3], dtype=int32)>

In [13]:
arr4 = tf.constant([[1,2,3,4,5],[2,3,4,5,6]])

In [ ]:
arr4

<tf.Tensor: shape=(2, 5), dtype=int32, numpy=
array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6]], dtype=int32)>

In [15]:
arr4[0].numpy()  # 2차 배열에서 0번 가져오기 

array([1, 2, 3, 4, 5], dtype=int32)

reshape 등 형태 변환하는 함수도 numpy와 동일하게 사용할 수 있습니다

In [16]:
tf.reshape(arr4, [5,2])  

<tf.Tensor: shape=(5, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 2],
       [3, 4],
       [5, 6]], dtype=int32)>

tf.variable을 통해 변수를 만들수도 있습니다.

https://www.tensorflow.org/guide/variable

In [18]:
a = tf.Variable([2.0, 3.0])

In [19]:
a

<tf.Variable 'Variable:0' shape=(2,) dtype=float32, numpy=array([2., 3.], dtype=float32)>

assign_add()를 통해 값을 더할 수 있습니다. 
변수이므로 계산값이 변수에 반영됩니다. 

In [20]:
a.assign_add([1,2])

<tf.Variable 'UnreadVariable' shape=(2,) dtype=float32, numpy=array([3., 5.], dtype=float32)>

In [21]:
a

<tf.Variable 'Variable:0' shape=(2,) dtype=float32, numpy=array([3., 5.], dtype=float32)>

tensor는 계산 속도가 중요하여 같은 타입끼리만 연산이 가능합니다. 

**  정수와 실수형이 연산되지 않습니다.
 
tf.cast()를 통해서 타입을 맞춰주어야 합니다. 

.dtype을 통해 데이터 타입 확인 가능합니다. (numpy도 동일합니다)

In [23]:
n1 =tf.constant(10)  # 정수
print(n1.dtype)   # .dtype을 통해 타입 확인 가능
n2 = tf.constant(5.) # 실수
print(n2.dtype)

<dtype: 'int32'>
<dtype: 'float32'>


In [25]:
n1+n2  # 타입이 맞지 않아서 에러가 발생함

InvalidArgumentError: ignored

cast()함수를 통해 형태를 변환할 수 있습니다.
* cast(변수, 새로운 데이터 타입)

In [26]:
n1 = tf.cast(n1, tf.float32)

In [27]:
n1+n2

<tf.Tensor: shape=(), dtype=float32, numpy=15.0>